name: sanity
on: [push, pull_request]
jobs:
  install-and-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install matplotlib
      - name: Import smoke tests
        run: |
          python - <<'PY'
          import torch, torch_geometric, numpy, sklearn
          print("Imports OK")
          PY
